import type { Metadata } from "next";
import { default as DefaultLayout } from "@/components/management/layouts/default";

export const metadata: Metadata = {
  title: "Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
